/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryPie: typeof import('./src/components/CategoryPie.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    KpiCard: typeof import('./src/components/KpiCard.vue')['default']
    RegionBar: typeof import('./src/components/RegionBar.vue')['default']
    TrendChart: typeof import('./src/components/TrendChart.vue')['default']
  }
}
